var empid = 54644654;
var empname = "Scott";
var empjob = "Manager";
var isPermanent = true;
var empsalary = "INR.45000";
var deptno = 10;
console.log("Employee Id : " + empid);
console.log("Employee Name : " + empname);
console.log("Employee Job : " + empjob);
console.log("Is Permanent Employee : " + isPermanent);
console.log("Employee Salary : " + empsalary);
console.log("Employee Department No. : " + deptno);
